[Feature] Janus mcq part component
Simon-Initiative/oli-torus pull request #1051
Opened 2021-05-13 14:19 UTC by dtiwarATS

-- Janus-MCQ as part component
--added type definition for MCQ
-- added UsePrevious hooks

2021-05-13 15:49 UTC, bsparks approved these changes

2021-05-13 18:21 UTC, darrensiegel requested changes
The files as part of this PR do not seem to have been "Prettified" using the prettier config found in the Torus repository under `assets/.prettierrc`. What jumped out at me was use of 3 and sometimes 4 spaces for indentations, where the Prettier config is set to 2. 

Please format all files using Prettier prior to opening a PR.

2021-05-14 05:31 UTC, dtiwarATS commented
fixed Prettier auto-formatting issue.

2021-05-14 15:34 UTC, bsparks approved these changes

2021-05-17 17:20 UTC, darrensiegel approved these changes

2021-05-17 17:20 UTC, merged