[BUGFIX] Carousel Part component
Simon-Initiative/oli-torus pull request #1139
Opened 2021-06-10 08:49 UTC by dtiwarATS

-- updated tag name for the Carousel component. It should be 'janus-image-carousel' not 'janus-carousel'

2021-06-10 14:52 UTC, bsparks commented on assets/src/components/parts/janus-Carousel/manifest.json
> +  "id": "janus_mage_carousel",
missing i

2021-06-10 14:56 UTC, dtiwarATS commented on assets/src/components/parts/janus-Carousel/manifest.json
> +  "id": "janus_mage_carousel",
Ooops... Done

2021-06-10 15:24 UTC, bsparks approved these changes

2021-06-14 10:59 UTC, darrensiegel requested changes

2021-06-14 10:59 UTC, darrensiegel commented on priv/repo/seeds.exs
> +    "janus_image_carousel",
Renaming this part component is not sufficient to allow existing Torus instances to pick up this change.  This renaming works for seeding new databases, but existing ones will end up having the old "janus_carousel' and a new 'janus_image_carousel' both exist as part components due to how `Oli.PartComponents.register_part_component' works.  

A database migration is necessary to do this "renaming" correctly.  The migration can simply delete the 'janus_carousel' record, allowing the seed.ex change to drive the creation of a new one with the updated id.

2021-06-15 06:09 UTC, dtiwarATS commented
Closing this PR for now. Once the migration script is ready and the rendering issues fixed then I will create another PR.

2021-06-15 06:09 UTC, closed without merging