Build Header Bar
Simon-Initiative/oli-torus pull request #1173
Opened 2021-06-17 14:08 UTC by schowkekarats360

2021-06-17 16:56 UTC, dsuriano requested changes

2021-06-17 16:56 UTC, dsuriano commented on assets/src/apps/authoring/HeaderNav.tsx
> +  console.log(content);
🗑

2021-06-17 16:56 UTC, dsuriano commented on assets/src/apps/authoring/HeaderNav.tsx
> +      <div className="col-7 btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
i think you can safely delete the `col-*` from these divs that are children of the `<nav>`. they are causing the header to show scrollbars the moment the screen is resized...

2021-06-21 12:13 UTC, dsuriano approved these changes
Tested locally and verified scrollbars fixed.

![2021-06-21 08 11 45](https://user-images.githubusercontent.com/633004/122759918-81bcd500-d268-11eb-8e04-08c46c57ae68.gif)

2021-06-22 16:42 UTC, schowkekarats360 commented
closing this one as latest PR is in place.

2021-06-22 16:42 UTC, closed without merging