[BUG FIX] Fix an issue where changing the title rendered the current slug invalid
Simon-Initiative/oli-torus pull request #1443
Opened 2021-08-24 16:59 UTC by eliknebel

This fixes an issue where changing the title of a page makes the current slug invalid by refreshing the page after a slug change. It also appears retain any subsequent edits between a title change and page reload.

Closes #848

2021-08-25 01:50 UTC, darrensiegel commented
This fix shouldn't be necessary.  There is server side slug resolution in place that allows editing to continue after a title change and continued use of an "invalid" slug.

I just did some testing and I don't see any problem.

2021-08-25 02:03 UTC, darrensiegel requested changes
This does work, in that it forces a refresh, but it does so only after the DeferredPersistenceStrategy reaches its quiet period.  So after editing the title, I have around two seconds before the reload happens, which could be jarring for a user and cause the user not to realize that it was the title edit that caused the release. 

Take another look here and see if there is an easy way to eliminate this delay.  One could either add a "flush" method to the strategy... or altogether side-step the strategy and in the case of a title edit directly invoke the persistence endpoint and when it finishes reload the page.

2021-08-29 15:37 UTC, eliknebel commented
Added a saveImmediate function to the persistence strategy which is called when the title changes.

2021-08-30 20:06 UTC, darrensiegel approved these changes

2021-08-30 20:11 UTC, darrensiegel approved these changes

2021-08-30 20:16 UTC, merged