[ENHANCEMENT] Export analytics / insights raw data
Simon-Initiative/oli-torus pull request #1576
Opened 2021-09-24 05:22 UTC by LEDThereBeLight

2021-09-24 10:59 UTC, darrensiegel requested changes
This downloads the derived analytics data.  What we need actually is a download of the "raw snaphot" data.

2021-09-27 03:37 UTC, LEDThereBeLight commented
> This downloads the derived analytics data. What we need actually is a download of the "raw snaphot" data.

I added the "raw" snapshot data minus the ids. The download lists all snapshots rather than aggregating by section/activity/objective.

Since the derived data download was already in place, I figured it was worth leaving in place.

2021-09-27 17:36 UTC, darrensiegel requested changes

2021-09-27 17:36 UTC, darrensiegel commented on lib/oli_web/live/insights/insights.ex
> +      "Section Slug"
Add in the creation date field

2021-09-27 17:56 UTC, darrensiegel approved these changes

2021-09-27 17:56 UTC, merged