Add missing default value to publishers default
Simon-Initiative/oli-torus pull request #2511
Opened 2022-05-10 12:13 UTC by gastonabella

2022-05-10 12:14 UTC, jrissler approved these changes

2022-05-10 13:13 UTC, mcass19 approved these changes

2022-05-11 18:44 UTC, darrensiegel requested changes
This updated migration won't run on any platform that has already had it applied.

2022-05-12 12:23 UTC, darrensiegel approved these changes

2022-05-12 12:23 UTC, merged