Some lti grade sync improvements/fixes
Simon-Initiative/oli-torus pull request #2847
Opened 2022-07-21 18:11 UTC by mcass19

Include the fix for [MER-1302](https://eliterate.atlassian.net/browse/MER-1302) and [MER-1261](https://eliterate.atlassian.net/browse/MER-1261).

PRs in the `lti_1p3` library:
- https://github.com/Simon-Initiative/lti_1p3/pull/21
- https://github.com/Simon-Initiative/lti_1p3/pull/22

2022-07-21 18:47 UTC, julmontesdeoca approved these changes
LGTM! 🚀

2022-07-21 19:14 UTC, gastonabella approved these changes
Great work! 🚀 🏅

2022-07-22 13:26 UTC, eliknebel requested changes

2022-07-22 13:26 UTC, eliknebel commented on mix.exs
>        {:lti_1p3_ecto_provider, "~> 0.3.1"},
We need to bump lti_1p3_ecto_provider here to 0.3.2, since it also relies on lti_1p3

2022-07-22 17:22 UTC, eliknebel approved these changes

2022-07-22 19:52 UTC, merged