[BUG FIX] Fix page link issues
Simon-Initiative/oli-torus pull request #3030
Opened 2022-09-27 23:07 UTC by eliknebel

This PR fixes the following issues related to page links:

- Styling when a page link is in a group with a purpose
<img width="899" alt="Screen Shot 2022-09-27 at 3 14 51 PM" src="https://user-images.githubusercontent.com/6248894/192652943-3210a7e7-8c22-41cc-8418-6fc508cc6328.png">

- Implements missing client side rendering of page links for activities
<img width="881" alt="Screen Shot 2022-09-27 at 3 10 23 PM" src="https://user-images.githubusercontent.com/6248894/192653011-4cac0815-cf0a-4d74-9738-6e040d08bb1a.png">
<img width="690" alt="Screen Shot 2022-09-27 at 3 10 18 PM" src="https://user-images.githubusercontent.com/6248894/192653013-7804ea2d-a4af-4499-b140-96f14ef00cde.png">

2022-09-27 23:22 UTC, darrensiegel approved these changes

2022-09-27 23:37 UTC, darrensiegel requested changes
I just realized that the page_link implementation "freezes" the original title of the page into the page_link element.  This content element should not store the page title of the linked page, rather, at rendering time (for both authoring and delivery) it should resolve the current title.  Take this example:

1. I create a page titled "Fuzzy Wuzzy"
2. I create another page and place a page_link in it to "Fuzzy Wuzzy"
3. I then rename the original page from "Fuzzy Wuzzy" to "Wuz a Bear"

The current impl will render the page link as "Fuzzy Wuzzy" since the title was caked into the page element in the second page.

2022-09-27 23:45 UTC, darrensiegel requested changes

2022-09-27 23:45 UTC, darrensiegel commented on assets/src/data/content/writers/html.tsx
> +        <div className="content-purpose-label">Checkpoint</div>
Should the purpose here be hardcoded as "Checkpoint"?

2022-09-28 00:38 UTC, eliknebel commented
Good point, I was trying to avoid adding another map for page names into the render context by just storing the title, however I didn't consider the case where pages are renamed. I will address this

2022-09-28 20:32 UTC, darrensiegel requested changes
I didn't correctly understand what the value of `ref` was in the page_link model. I assumed it was a resource_id.  The fact that it is a link, which then this code parses out the slug and uses the `pageTitles` to retrieve the title is problematic for the case when the slug of a page changes (due to its title being changed).  Upstream, the `Oli.Resources.page_titles` builds a map of the "latest" revision slug to its title.  But there can be "old" slugs littered throughout content which will break title rendering with this approach. 

Moreover, the cost of building the page titles map is not small.  It fetches all page revisions (e.g. there are 511 pages in Chemistry I), just to get to the titles and build that map.  It does that on every page render, even when there are no page_title instances present.

Instead, I think we need to do this:

1. Change the model of the `page_link` from `ref` to `idref`.  Simply embed into `idref` the resource_id of the page linked to.
2. Leverage a good assumption that at most a page will contain one or two `page_link` instances. Replace the page_titles map with a targeted function that takes a resource_id and returns the title of the resolved revision.  Call this when needed during rendering.  
3. Let's just cut the cord and remove the ability to embed `page_link` instances within Activities. That simplifies a bunch of this.

2022-09-30 18:36 UTC, darrensiegel approved these changes

2022-09-30 18:46 UTC, merged