[FEATURE] [MER-1696] Student oriented summary view
Simon-Initiative/oli-torus pull request #3272
Opened 2023-02-17 14:40 UTC by simonchoxx

[MER-1696](https://eliterate.atlassian.net/browse/MER-1696)

This PR aims to shows a "Discussion" link in the left navigation bar, which when clicked takes the student to a view showing two groups of publications.  

- Summary of all their publications in all collaboration spaces.

- Summary of other students most recent publications in all collaboration spaces. 

We only need to think about some kind of pagination in case we want to show more than x amount of posts. Do you think it could be possible to do it in another ticket maybe @darrensiegel?

![Captura de pantalla 2023-02-17 a la(s) 10 57 10](https://user-images.githubusercontent.com/16328384/219676185-d7f31c08-39a9-46ab-8032-83060dfb76de.png)

![Captura de pantalla 2023-02-17 a la(s) 10 58 07](https://user-images.githubusercontent.com/16328384/219676197-c8deb8ee-8e73-469b-bfc8-4b3f68003dd6.png)

[MER-1696]: https://eliterate.atlassian.net/browse/MER-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-02-17 16:03 UTC, darrensiegel requested changes

2023-02-17 16:03 UTC, darrensiegel commented on lib/oli/resources/collaboration.ex
> +            rev.deleted == false,
This is good thinking, to exclude posts from pages that were once part of the course but are now deleted, but it isn't necessary to do this.  When a page is deleted (by an author), and that new publication is applied to a course section, the section resource record that had corresponded to that page gets deleted from the course section.  So I think you can simplify this query by locating posts through only a join of SectionResource records.

2023-02-17 16:03 UTC, darrensiegel commented on lib/oli/resources/collaboration.ex
> +            rev.deleted == false,
Same comment as above, this can be simplified to only join through SectionResource.

2023-02-17 16:03 UTC, darrensiegel commented on lib/oli_web/components/delivery/discussion_board.ex
> +  @posts_limit 5
I think that this is perfect for now.  We show the student at most, their five most recent posts, and at most the five most recent posts by their classmates.  No need to make this a paged table and allow arbitrarily deep access.

2023-02-17 16:04 UTC, darrensiegel commented
Also, we should remove the two buttons "Create Study Group" and "Add Discussion".  These represent features that a student cannot actually perform.

2023-02-28 18:33 UTC, augusto1024 approved these changes
LGTM 🚀

2023-02-28 18:33 UTC, augusto1024 commented on lib/oli/resources/collaboration.ex
> +            sr.numbering_level > 0,
NIT: Once we allow posts at the course level, we might want to change this to be `sr.numbering_level == 0`. This is just something to keep in mind. We don't need to change it now 😁

2023-02-28 18:52 UTC, darrensiegel approved these changes

2023-02-28 18:52 UTC, merged