[MER-1992] Improve product search capability
Simon-Initiative/oli-torus pull request #3729
Opened 2023-06-19 17:42 UTC by simonchoxx

[MER-1992](https://eliterate.atlassian.net/browse/MER-1992)

This PR adds the possibility to search also by the title of the base project of the product. 

So, in the search bar it will be possible to search both by product title and by title of the product base project. 

It's also verified that the sorting by date of creation is using the `inserted_at` field of the database.

https://github.com/Simon-Initiative/oli-torus/assets/16328384/63ee6e0e-48ea-4718-941c-8302a556660e

2023-06-21 18:22 UTC, eliknebel requested changes
I think there is still an issue with sorting on creation date. Can we verify that the date being rendered is actually the product date (and not the project date). The date rendered in the column should match the date being used to sort on

<img width="1216" alt="Screenshot 2023-06-21 at 2 09 17 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/6248894/38352b15-56b4-4e84-9dfe-298d4503215d">

2023-06-21 19:00 UTC, simonchoxx commented
Excuse me @eliknebel, but are you looking at the same view I'm working on? Because in the image you attached in the search bar there are 2 buttons 'search' and 'reset' and in the product view I'm working on I only have the 'search' button (along with a cross icon to delete the content). 
Here is a video of how the table is currently working for me.


https://github.com/Simon-Initiative/oli-torus/assets/16328384/e19ddfab-6341-4412-8ae3-28b2c84b3c17

2023-06-21 19:26 UTC, eliknebel commented
I believe it is. I think the difference is that this is on our production server proton `https://proton.oli.cmu.edu/admin/products` and therefore it may have some minor differences since the last version that was pushed. I think here it appears the reset was refactored into the text box as an "x"

2023-06-21 19:28 UTC, eliknebel commented
Just verified the latest in tokamak is exhibited the same sorting behavior. I assume it is still and issue since I didnt see any changes in the PR related to the name or sorting of this column
<img width="1621" alt="Screenshot 2023-06-21 at 3 27 12 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/6248894/d57b769f-2903-4222-af00-560ec38ea053">

2023-06-22 14:50 UTC, eliknebel approved these changes
Nice work

2023-06-22 14:50 UTC, merged