[MER-2167] Summative Assessment Analytics - Part 2
Simon-Initiative/oli-torus pull request #3774
Opened 2023-06-26 23:45 UTC by nicocirio

[Link](https://eliterate.atlassian.net/browse/MER-2167?filter=10069) to the ticket

### Multiple choice
![image](https://github.com/Simon-Initiative/oli-torus/assets/74839302/c85c9bfe-e141-44d1-ab42-a6e81bdcf2ef)

### Short Answer
![image](https://github.com/Simon-Initiative/oli-torus/assets/74839302/bb21f9d0-a339-4d03-9738-ebc3dffb4c3e)

2023-06-27 15:20 UTC, augusto1024 approved these changes
LGTM 🚀

2023-06-27 15:20 UTC, augusto1024 commented on lib/oli_web/components/delivery/scored_activities/scored_activities.ex
> +          |> Enum.frequencies()
I didn't know about this function 🙌

2023-06-28 20:28 UTC, darrensiegel requested changes
This impl can't be taken as-is as it isn't robust against the fact that activities can structurally change from revision to revision.  Consider the following scenario:

1. An MCQ is published which contains 3 choices.
2. A student takes a quiz with that MCQ and picks choice A.
3. Author revises the activity to remove choice A, republishes course.
4. Instructor goes to view the Scored Activities for that page.

The line I noted in the review breaks with:

```
key :id not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
```

2023-06-28 20:28 UTC, darrensiegel commented on lib/oli_web/components/delivery/scored_activities/scored_activities.ex
> +            Map.merge(choice, %{"frequency" => Map.get(frequency_per_choice_id, choice["id"])})
This is not robust against the possibility that choices can be removed in later revisions of an activity.

2023-06-29 10:47 UTC, darrensiegel commented
I am retargeting this work to version 25. 

I'm concerned about the performance impact (particularly memory footprint) of fetching all activity and part attempts in the manner that this is doing - and especially landing this so close to the end of the development cycle. 

Also, I've filed: https://eliterate.atlassian.net/browse/MER-2228, which needs to be done to fix performance issues for this implementation, which exist on `master`

2023-06-29 10:47 UTC, closed without merging