[MER-2481] My courses view for instructors
Simon-Initiative/oli-torus pull request #4122
Opened 2023-08-18 16:52 UTC by nicocirio

[Link](https://eliterate.atlassian.net/browse/MER-2481) to the ticket

https://github.com/Simon-Initiative/oli-torus/assets/74839302/460de448-c09e-4f04-bca1-af0efcf60a1b

This PR also implements `verified_routes` allowing us to use the new sigil `~p` to define URLs. 
More info about this feature can be found [here](https://phoenixframework.org/blog/phoenix-1.7-final-released)

2023-08-18 18:57 UTC, augusto1024 reviewed
Great job! I really love the `verified_routes` thing (i hate having to go to the router and see how I can access the route using the routes helper 😠).

I left some minor comments 😁

2023-08-18 18:57 UTC, augusto1024 commented on lib/oli_web.ex
> +        statics: OliWeb.static_paths()
❤️

2023-08-18 18:57 UTC, augusto1024 commented on lib/oli_web/components/delivery/instructor_dashboard.ex
> +              <% end %>
NIT: This looks like a good opportunity to replace that `<%= if badge do %>` for LiveView's new `:if` decorator 😁

2023-08-18 18:57 UTC, augusto1024 commented on lib/oli_web/components/delivery/instructor_dashboard.ex
> +        <%= for %TabLink{label: label, path: path, badge: badge, active: active} <- @tabs do %>
NIT: This looks like a good opportunity to replace that `<%= for... do %>` for LiveView's new `:for` decorator 😁

2023-08-18 18:57 UTC, augusto1024 commented on lib/oli_web/controllers/pow/registration_html/edit.html.heex
> +      <%= link "Cancel", to: value_or(assigns[:cancel_path], Routes.live_path(@conn, OliWeb.Delivery.OpenAndFreeIndex)), class: "btn btn-md btn-outline-secondary btn-block mt-3" %>
Can't we change this for `~p"/sections"` like in the other files?

2023-08-18 18:57 UTC, augusto1024 commented on lib/oli_web/live/delivery/open_and_free_index.ex
> +  on_mount(OliWeb.LiveSessionPlugs.SetCtx)
❤️

2023-08-18 18:57 UTC, augusto1024 commented on lib/oli_web/live/delivery/open_and_free_index.ex
> +    end)
WDYT about moving this query to the `lib/oli/delivery/sections.ex` context file?

2023-08-21 13:57 UTC, augusto1024 approved these changes
Thanks for the changes 🙌

2023-08-21 14:44 UTC, darrensiegel requested changes

2023-08-21 14:44 UTC, darrensiegel commented on lib/oli/delivery/sections.ex
> +          s.id in ^section_ids and s.status == :active and e.status == :enrolled and
We shouldn't be including `s.status == :active` here.  If client code is passing in a list of section_ids, that client code might not be making the same assumptions that they only want results to return if the section is "active".

2023-08-25 11:39 UTC, darrensiegel approved these changes

2023-08-25 11:40 UTC, merged