[FEATURE][MER-2681] Redesing changes visualization publish view
Simon-Initiative/oli-torus pull request #4363
Opened 2023-10-26 23:43 UTC by simonchoxx

[MER-2681](https://eliterate.atlassian.net/browse/MER-2681)

This PR redesigns the way publication changes are rendered in the `publish view`. 

It adds a table showing title, change type and categorization of changes.

If the categorization is `structural`, the whole row is highlighted in grey color. 

Feel free to suggest design changes to display the data in the table. 

![Captura de pantalla 2023-10-26 a la(s) 20 39 45](https://github.com/Simon-Initiative/oli-torus/assets/16328384/8ad81636-0644-4069-8943-e631fceff57e)

2023-10-27 13:13 UTC, darrensiegel requested changes
Code changes all look good.

The only thing that I think we need to change is to remove the "center alignment" of the table columns.  They should all just be left aligned.

2023-10-27 13:29 UTC, bitbldr commented
Are structural/non-structural the right terms here? I'm not sure the average user is going to know what those mean. Would Major/Minor be better since we already have prior art below explaining what those mean to the user?

2023-10-27 17:15 UTC, simonchoxx commented
@darrensiegel @bitbldr Yes, I was guided by the ticket description to use `Structural` or `Non-structural` in that column. 

If you think it's clearer for the user to change it to "Major"/"Minor", I will change it without problems.

2023-11-02 23:59 UTC, darrensiegel approved these changes

2023-11-02 23:59 UTC, merged