[FEATURE] [MER-3129] Email notification on existing email account
Simon-Initiative/oli-torus pull request #4795
Opened 2024-05-08 18:27 UTC by simonchoxx

[MER-3129](https://eliterate.atlassian.net/browse/MER-3129)

This PR modifies the functions to create new `student/instructor` and `author` user accounts, in order to send an email to the user in case the account has already been registered with the email that is being used to create the new account.

In addition, the flash messages that are displayed to users if they try to create an account with an existing email address are modified.

- Create a Learner/Educator Account

https://github.com/Simon-Initiative/oli-torus/assets/16328384/8afc65f5-a8e0-40e4-8791-ad2742c07947

- Create an Authoring Account

https://github.com/Simon-Initiative/oli-torus/assets/16328384/3b566791-c03b-487a-824b-fcd71400af93

2024-05-08 19:44 UTC, tomasferok reviewed
Nice Work  Santi !!! 💯 💯

2024-05-08 19:44 UTC, tomasferok commented on lib/oli_web/pow/author_context.ex
> +      %Author{email: email} = author ->
WDYT about separate this logic in small functions, something like that:  
def create(params) do
    case Accounts.get_author_by_email(params["email"]) do
      %Author{email: email} = author ->
        if author.email_confirmed_at do
          email_already_registered(email)
        else
          {:error, %{email: "has already been taken"}}
        end
  
      _nil ->
        create_new_author(params)
    end
  end
  
  
  
  defp email_already_registered(email) do
    Oli.Email.create_email(
      email,
      "Account already registered",
      "email_already_registered.html",
      %{
        url: Routes.authoring_pow_session_path(OliWeb.Endpoint, :new),
        forgot_password:
          Routes.authoring_pow_reset_password_reset_password_path(OliWeb.Endpoint, :new)
      }
    )
    |> Oli.Mailer.deliver_now()
    {:error, %{email: "has already been taken"}}
  end
  
  defp create_new_author(params) do
    %Author{}
    |> Author.changeset(params)
    |> Repo.insert()
    |> case do
      {:ok, author} ->
        {:ok, author}
  
      {:error, error} ->
        {:error, error}
    end
  end

2024-05-08 19:44 UTC, tomasferok commented on lib/oli_web/pow/messages.ex
> +      case conn.assigns.action do
Puting this in other function can be also good WDYT? 
something like:
  defp get_user_for_confirmation("/authoring/registration", email), do: Accounts.get_author_by_email(email)
  defp get_user_for_confirmation("/registration", email), do: Accounts.get_user_by(%{email: email})
  defp get_user_for_confirmation(_, email), do: nil

2024-05-08 19:44 UTC, tomasferok commented on lib/oli_web/pow/user_context.ex
> +        if user.email_confirmed_at,
I think is a very similar logic than in the author context what about doing the same here?

2024-05-09 13:27 UTC, eliknebel requested changes

2024-05-09 14:16 UTC, simonchoxx commented on lib/oli_web/pow/messages.ex
> +      {user, _} when not is_nil(user.email_confirmed_at) ->
Thanks for your recommendation. I will leave this as it was before.

2024-05-09 14:53 UTC, Francisco-Castro approved these changes
Great work here!

I've left you some comments, but they are not blockers.

Could you please update the [documentation](https://github.com/Simon-Initiative/oli-torus/blob/ad0b9237a203ab4dccc97e2e4618223c933f4150/lib/oli_web/pow/messages.ex#L44) for the `pow_email_confirmation_email_confirmation_required/1` function now that it's handling two tasks?

2024-05-09 14:53 UTC, Francisco-Castro commented on lib/oli_web/pow/author_context.ex
> +        {:error, %{email: "has already been taken"}}
I could track where the map returned by this error goes and if it is used later on. Do you know where it is sent?

2024-05-09 14:53 UTC, Francisco-Castro commented on lib/oli_web/pow/author_context.ex
> +            |> Oli.Mailer.deliver_now()
NIT: We have the `Oli.Email` module that contains email-related functionalities. Perhaps relocating the `create_email` function from its current location to the mentioned module, and renaming it to something like `email_has_been_taken`. What do you think?

2024-05-16 11:05 UTC, darrensiegel approved these changes

2024-05-16 11:06 UTC, merged