[ENHANCEMENT] [N23-169] Course header UI improvement
Simon-Initiative/oli-torus pull request #4806
Opened 2024-05-14 13:45 UTC by nicocirio

[Link](https://eliterate.atlassian.net/browse/NG23-169) to the ticket

### Before
https://github.com/Simon-Initiative/oli-torus/assets/74839302/52815b29-9d12-43e1-b017-c46628c4e73d

#### Student without a profile picture
![Screenshot 2024-05-14 at 10 42 53 AM](https://github.com/Simon-Initiative/oli-torus/assets/74839302/69d18219-c33c-42fb-97bc-570bd42201a0)

### After
https://github.com/Simon-Initiative/oli-torus/assets/74839302/2803fbef-984e-4f6a-9422-8d4bca8ff264

#### Student without a profile picture
![Screenshot 2024-05-14 at 10 42 18 AM](https://github.com/Simon-Initiative/oli-torus/assets/74839302/6ee19a34-c8f5-48a9-b2a2-721465477295)

2024-05-14 15:10 UTC, Francisco-Castro commented on lib/oli_web/components/delivery/user_account.ex
> +  defp to_initials(_), do: "?"
I couldn't see the criteria in the ticket for how to take the initials. Could you please put it here?

2024-05-14 17:19 UTC, eliknebel approved these changes

2024-05-14 17:30 UTC, eliknebel requested changes
<img width="482" alt="Screenshot 2024-05-14 at 1 29 06 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/6248894/6b9c03bb-f318-444e-8ab7-5d7fb0392805">

While testing locally, I noticed when in a course as a guest, the "Leave Course" link overflows off the page

2024-05-16 16:22 UTC, eliknebel approved these changes

2024-05-16 16:22 UTC, merged