[ENHANCEMENT] [NG23-178] Improve navigation when prev or next resource is a section or subsection
Simon-Initiative/oli-torus pull request #4857
Opened 2024-06-04 18:22 UTC by gastonabella

[NG23-178](https://eliterate.atlassian.net/browse/NG23-178)

Set the following as a lesson navigation rule:
1. If the next or previous page is a **unit** or **module**, redirect the student to the Learn view (`/sections/{SECTION_SLUG}/learn`), highlighting the container.
2. Otherwise, redirect to the specified resource view (`/sections/{SECTION_SLUG}/lesson/{RESOURCE_SLUG}`) (page, section, or subsection).

**Before:**

https://github.com/Simon-Initiative/oli-torus/assets/26532202/a373d684-a4b9-4a0c-ac28-333e7129a995

**After:**

https://github.com/Simon-Initiative/oli-torus/assets/26532202/5a1f1da6-1277-4142-9eb4-16dd2acc1f13

2024-06-05 13:01 UTC, darrensiegel requested changes
I verified my suspicion by testing this locally: this change now renders "sections" and "sub-sections" as pages, visible to the user.  Consider the following course structure:

```
Unit1
  Module1
     Section1
         page1
         page2
     Section2
         page3
```

If a student is viewing page2 and clicks "Next", they should next see page3.  This impl, however, renders "Section2" as a page.

2024-06-05 16:57 UTC, gastonabella commented
> I verified my suspicion by testing this locally: this change now renders "sections" and "sub-sections" as pages, visible to the user. Consider the following course structure:
> 
> ```
> Unit1
>   Module1
>      Section1
>          page1
>          page2
>      Section2
>          page3
> ```
> 
> If a student is viewing page2 and clicks "Next", they should next see page3. This impl, however, renders "Section2" as a page.


I agree that we should not be showing sections and subsections as pages, but this behavior is inherited and caused by the current logic under the `Oli.Delivery.PreviousNextIndex` (and the `:previous_next_index` field in `Sections`). There we are considering both **pages** and **containers** as navigable resources when building this structure. There are several options, but I have two at the top of my head:

**A.** Update how the `previous_next_index` structure is built to ignore sections and subsections. Since this structure is mainly used for navigation, I don't see the purpose of retrieving these containers. We should rebuild and update this field on all sections too.

**B.** Keep the current structure but update how it is navigated so we skip sections. Therefore, every time we need to determine what the next/prev resource should be, we iterate over the structure until we find a page or a module/unit.

My only concern is that sections and subsections would lose visibility while navigating through pages. They would only be seen on the Learn page.

Any ideas?

2024-06-05 17:05 UTC, darrensiegel commented
@gastonabella Actually now that I think about it, there is a third option here:  Instead of skipping section and sub-sections, we do render them.  But we render them not as pages, but as a container.  This is how v27 works.

Rendering these resources as a container simply means that we render a table of contents for the pages contained in that container.  

Then when a student clicks "Next" again, the will be taken to the first page in that section.

2024-06-05 17:23 UTC, gastonabella commented
> @gastonabella Actually now that I think about it, there is a third option here: Instead of skipping section and sub-sections, we do render them. But we render them not as pages, but as a container. This is how v27 works.
> 
> Rendering these resources as a container simply means that we render a table of contents for the pages contained in that container.
> 
> Then when a student clicks "Next" again, the will be taken to the first page in that section.

@darrensiegel I like that approach! Does that table of contents already exist? Are there any Figma designs?
Even though we could do it on this PR, I prefer to be consistent and keep following the design's good practices as for NG.

2024-06-05 17:31 UTC, darrensiegel commented
That Table of contents implemetnation still exists in the code.  The template that it used is `lib/oli_web/templates/page_delivery/container.html.heex`

But i'm quite sure that it hasn't been updated for NG designs.

2024-06-10 14:49 UTC, gastonabella commented
@darrensiegel I've just pushed the changes based on the discussion in the Jira ticket comments. The decision was to skip units and sections in the footer navigation and redirect to the Learn page when navigating to a module. This is a temporary workaround to avoid the current behavior. However, I agree that we should aim for a final version where we can navigate to units and sections as well, and build something like a table of contents once we have the designs. I updated the "After" recording so you can see how it works now.

2024-06-12 13:50 UTC, eliknebel approved these changes

2024-06-13 10:33 UTC, darrensiegel requested changes
We do not want to skip Units.  We only want to skip sections and subsections. 

If we skip units, students will bypass Unit intro videos.

2024-06-13 15:25 UTC, gastonabella commented
@darrensiegel sounds good! I've just pushed the changes.

2024-06-13 21:42 UTC, darrensiegel approved these changes

2024-06-13 21:42 UTC, merged