[FEATURE] [NG23-176] Set course welcome title and encouraging subtitle as author and instructor
Simon-Initiative/oli-torus pull request #4887
Opened 2024-06-14 19:47 UTC by gastonabella

[NG23-176](https://eliterate.atlassian.net/browse/NG23-176)

Changes introduced:
- Add new `welcome_title` and `encouraging_subtitle` fields to the `projects` and `sections` table.
- Allow setting and editing these fields as a project or product author and as a section instructor.
- Display both the Welcome Title and Encouraging Subtitle on the student's homepage.

**Scenario 1: Set the Welcome Title and Encouraging Subtitle as a project's author and create a section that inherits these fields.**

https://github.com/Simon-Initiative/oli-torus/assets/26532202/03146ab4-fdc3-4268-92cd-6c41dd8213d9

**Scenario 2: Set the Welcome Title and Encouraging Subtitle as a product's author and create a section that inherits these fields.**

https://github.com/Simon-Initiative/oli-torus/assets/26532202/7c63ed4e-fcc9-4155-b95d-2b6dfca3372c

**Scenario 3: Set the Welcome Title and Encouraging Subtitle as a section's instructor and see these fields when visiting the course homepage as a student.**

https://github.com/Simon-Initiative/oli-torus/assets/26532202/995a1126-833a-4d00-bd4e-35bdb6c2551f

2024-06-14 20:06 UTC, darrensiegel requested changes
One minor change and also:

For the project, we should add support for export and import to preserve the welcome title and encouraging subtitle of the project and any products that the project contains.

2024-06-14 20:06 UTC, darrensiegel commented on priv/repo/migrations/20240611141718_add_welcome_title_and_encouraging_subtitle_to_sections.exs
> +  use Ecto.Migration
Collapse these two migrations into one

2024-06-18 20:22 UTC, gastonabella commented
@darrensiegel this is ready for review again. Let me know if something else needs to be changed 🙌

2024-06-21 00:32 UTC, darrensiegel approved these changes

2024-06-24 11:23 UTC, merged