[FEATURE] [MER-3703] Add cover image editing at the section level
Simon-Initiative/oli-torus pull request #5124
Opened 2024-09-23 17:41 UTC by rgachuhi

This PR supports changing the section cover image in the course section's delivery interface. 
![Screenshot 2024-09-23 at 1 41 06 PM](https://github.com/user-attachments/assets/962be569-a459-4283-865f-8cb0372f1ab5)

2024-09-24 15:04 UTC, Francisco-Castro requested changes
I tested the code locally, and it's working as expected. The only part I noticed is the flash message not appearing when successfully uploading an image.

Could you please take a look at it?

Note: I left a few suggestions for you."

2024-09-25 18:23 UTC, rgachuhi commented on lib/oli_web/live/sections/overview_view.ex
> +      </Group.render>
Suggested tweaks applied

2024-09-25 18:23 UTC, rgachuhi commented on lib/oli_web/live/sections/details/image_upload.ex
> +defmodule OliWeb.Sections.Details.ImageUpload do
thanks

2024-09-25 18:25 UTC, rgachuhi commented on lib/oli_web/live/sections/overview_view.ex
> +    with uploaded_path <- Enum.at(uploaded_files, 0),
Suggestion applied

2024-09-25 19:24 UTC, merged