[BUG FIX] [MER-3841] Make PageContent traversal functions hit content in properties like caption
Simon-Initiative/oli-torus pull request #5179
Opened 2024-10-08 17:57 UTC by andersweinstein

Citations in image captions were found to get broken on export/ingest. This happened because the required rewiring process was not hitting them because it used functions from the PageContent module which only traverse through element children, and caption content is in a caption property, not children. This PR implements a general solution to modify the PageContent map_reduce-style functions to visit and process content in properties like the caption property of an image element, and also the relevant properties of a popup element, as is done correctly in the code that rewires links.

2024-10-09 16:55 UTC, darrensiegel requested changes
We need to prove this works via a unit test

2024-10-09 17:31 UTC, andersweinstein commented
> We need to prove this works via a unit test

OK, how extensive a test do you want? Just the case that motivated this, citations in captions? I verified it on ingest/export with a minimal one-page-with-one-image-with-caption course. Could turn the json into a unit test, I suppose.

2024-10-16 21:37 UTC, andersweinstein commented
I grasp now that there are two different sets of content traversing `map_reduce` functions in the codebase, one in `Oli.Resources.PageContent`, and another near duplicate set in `Oli.Publishing.UniqueIds` and they behave differently:

-The UniqueId versions are described in the code as differing in order to take "stop" and "ignore" parameters to control their traversal. 
- But another difference is that the top-level PageContent map_reduce function does NOT descend into structured content blocks (type="content") at all. (Presumably it was intended for locating activities, not traversing the content element tree). 

The PageContent module also includes functions like `item_with_children`. This can be used within a suitable outer loop or map function to traverse into structured content where that is desired. It is **this** method that is used by the ingestion/export code to find and process citations.

This seems very unfortunate.  But in any case: the current change fixes `item_with_children` within the the PageContent module so it will visit content elements in properties when used for that purpose. It's possible the same fix ought to be added to unique_ids. But the present issue was the rewiring of citations on ingest.

2024-10-17 12:13 UTC, andersweinstein commented
Minimal one-page test course including citation in image caption that can be used to test ingest and export->ingest again.

[anders_citation_test.zip](https://github.com/user-attachments/files/17412114/anders_citation_test.zip)

2024-10-22 12:13 UTC, darrensiegel approved these changes

2024-10-22 12:13 UTC, merged