[FEATURE] [MER-3189] Learning Objectives Proficiency distribution chart
Simon-Initiative/oli-torus pull request #5251
Opened 2024-11-12 20:28 UTC by manelli

See: https://eliterate.atlassian.net/browse/MER-3189

2024-11-25 21:15 UTC, simonchoxx requested changes
Good job! 🏅

I have found a couple of things that we should change. 

- When clicking to sort by some column multiple charts appears. See the following image:

![Captura de pantalla 2024-11-25 a la(s) 6 06 58 p  m](https://github.com/user-attachments/assets/a95c58a0-65bc-4309-83a0-f32fbf361168)

- Sort by **PROFICIENCY DISTRIBUTION** is blocked by the chart tooltip 

![Captura de pantalla 2024-11-25 a la(s) 6 11 32 p  m](https://github.com/user-attachments/assets/062169b1-cb4f-47bb-a88e-019d928a571d)

I also left you a comment about the chart colors.

2024-11-30 07:18 UTC, manelli commented
Fixed the colors for the chart to reflect the Figma design

<img width="1270" alt="image" src="https://github.com/user-attachments/assets/200a6fcd-d188-4604-a9aa-91298757bc5e">

2024-12-02 13:44 UTC, darrensiegel approved these changes

2024-12-02 13:45 UTC, darrensiegel approved these changes

2024-12-02 13:45 UTC, merged