Project visibility
Simon-Initiative/oli-torus pull request #785
Opened 2021-02-04 02:55 UTC by rgachuhi

This PR adds a feature to allow course publishers the ability to control who is allowed to create course instances for a particular course project. By default, any author to the course project has the ability to login to their Torus linked LMS, select a course project and build a course instance. This feature allow additional controls, whereby a publisher can choose to give global builder access or limit the access to only a select group of users or institutions.

Requires mix deps.get (updates ecto_sql to v3.5.2)

2021-02-05 14:35 UTC, darrensiegel requested changes
A couple of small code changes that I pointed out inline.

Also, I believe strongly that we need to move the Visibility LiveView *out* of the current page that it is located within.  Take a look at the attached screenshot of what this looks like as one starts making changes to a course.  The list of outstanding updates pushes the visibility view down, and will be difficult for users when that list becomes long.  I'm fine with the Visibility view being moved to the project Overview view, and placed under "Collaborators". 

![Screen Shot 2021-02-05 at 9 17 40 AM](https://user-images.githubusercontent.com/7431756/107047093-6d82aa80-6795-11eb-8d09-cee80fdd9f8a.png)

2021-02-06 15:28 UTC, rgachuhi commented on lib/oli/institutions.ex
> +  def search_authors_matching(query) do
Name changed

2021-02-06 15:29 UTC, rgachuhi commented on lib/oli_web/templates/project/insights.html.eex
> +      <h1>Insights</h1>
👍

2021-02-06 15:31 UTC, rgachuhi commented on priv/repo/migrations/20210128145315_create_project_visibilities.exs
> +      add :project_id, :integer
switched fields to foreign key refs

2021-02-06 15:33 UTC, rgachuhi commented
> A couple of small code changes that I pointed out inline.
> 
> Also, I believe strongly that we need to move the Visibility LiveView _out_ of the current page that it is located within. Take a look at the attached screenshot of what this looks like as one starts making changes to a course. The list of outstanding updates pushes the visibility view down, and will be difficult for users when that list becomes long. I'm fine with the Visibility view being moved to the project Overview view, and placed under "Collaborators".
> 
> ![Screen Shot 2021-02-05 at 9 17 40 AM](https://user-images.githubusercontent.com/7431756/107047093-6d82aa80-6795-11eb-8d09-cee80fdd9f8a.png)

I have moved the package visibility UI into the project overview page.

2021-02-08 16:30 UTC, darrensiegel approved these changes

2021-02-08 16:31 UTC, merged