Fix CATA Feedback + Activity Hints
Simon-Initiative/oli-torus pull request #949
Opened 2021-04-14 14:29 UTC by LEDThereBeLight

Pulled out the bug fixes from a larger activity testing branch since I ran into some test setup problems that I need to fix.

**Bug Fixes**
- Check all that apply: fix feedback/score not showing up in delivery
- Hints: fix hint requests and display in all activities when empty hints are present

2021-04-14 14:38 UTC, LEDThereBeLight commented
There's a merge from master issue here causing a build failure - fixing it

2021-04-14 14:57 UTC, eliknebel commented
<img width="971" alt="Screen Shot 2021-04-14 at 10 57 19 AM" src="https://user-images.githubusercontent.com/6248894/114732022-32aa6f00-9d10-11eb-9cf1-7c0e8b9f8717.png">

I'm still seeing an issue with no feedback in the activity live preview. Was this supposed to fix that as well?

2021-04-14 15:26 UTC, eliknebel requested changes

2021-04-14 15:26 UTC, eliknebel commented on assets/src/components/resource/TestModeHandler.tsx
> -    .then((result: Persistence.Evaluated) => {
This is the fix for the feedback in live preview that should remain intact

2021-04-14 15:27 UTC, eliknebel commented on assets/src/components/resource/TestModeHandler.tsx
> -    continuation({ type: 'success', actions: evaluatedParts }, undefined);
this must remain named 'actions' as well

2021-04-14 15:35 UTC, eliknebel requested changes

2021-04-14 15:35 UTC, eliknebel commented on assets/src/components/resource/TestModeHandler.tsx
> -      continuation({ type: 'success', actions }, undefined);
This should remain named 'actions'

2021-04-15 00:51 UTC, darrensiegel commented on assets/src/components/resource/TestModeHandler.tsx
> -            type: 'FeedbackAction',
This should remain "FeedbacAction"

2021-04-16 05:09 UTC, closed without merging